name: Test Screenshot Action

on:
  pull_request:
    branches:
      - master
permissions:
  issues: write
  pull-requests: write
jobs:
  test_screenshot_action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Take screenshot and post it on the PR
      uses: ./
      with:
        url: 'https://google.com'
        dropbox_token: ${{ secrets.DROPBOX_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

